AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: resJam serverless backend service

Resources:
  resJamProjectLambda:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.handler
      Runtime: nodejs16.x
      CodeUri: project_function/project/
      Layers:
        - !Ref resJamNodeModuleLayer
        - !Ref resJamUtilityModuleLayer

  resJamUserLambda:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.handler
      Runtime: nodejs16.x
      CodeUri: user_function/user/
      Layers:
        - !Ref resJamNodeModuleLayer
        - !Ref resJamUtilityModuleLayer

  resJamNodeModuleLayer:
    Type: AWS::Serverless::LayerVersion
    Properties: 
      LayerName: resJam-node-module
      Description: node modules
      ContentUri: lambda_layers/resJam-node-module/
      CompatibleRuntimes: 
        - nodejs16.x

  resJamUtilityModuleLayer:
    Type: AWS::Serverless::LayerVersion
    Properties: 
      LayerName: resJam-utility-module
      Description: node modules
      ContentUri: lambda_layers/resJam-utility-module/
      CompatibleRuntimes: 
        - nodejs16.x
